server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://10.63.11.29:3307/shopstore?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    #3.为了便于查询JSON数据，隐藏没有值的属性，减少流量的消耗，服务器不应该向客户端响应为NULL的属性。可以在属性或类之前添加@JsonInclude(value=Include.NON_NULL)，也可以在application.properties中添加全局的配置。
    #服务器向客户端不响应为null的属性
    jackson:
      default-property-inclusion: NON_NULL
  servlet:
    multipart:
      #spring设置最大值的file size
      maxFileSize: 10MB
      maxRequestSize: 10MB
    #4.SpringBoot项目的默认访问名称是“/”，如果需要修改可以手动在配置文件中指定SpringBoot 2.x访问项目路径的项目名。不建议修改。
#   context-path: /store

#配置mybatis父路径
mybatis:
  mapper-locations: classpath:mapper/*.xml

#4.在application.properties文件中添加收货地址数据上限值的配置。.
user:
  address:
    max-count: 20

